### ISSUE TITLE
Add skeleton loader

### ISSUE THREAD

**Issue by Bartek532** [Bartek532/syncreads#47]

**Comment by Evcat6** [comment]
I can do this)

**Comment by Bartek532** [comment]
@Evcat6 sure, thanks! Just open a pull request when you're ready 🙂

**Comment by Evcat6** [comment]
Can you little bit information about skeleton what i have to implement?

**Comment by Bartek532** [comment]
@Evcat6 what questions do you have? The goal of this is to replace our generic loader which is overlaping the whole page now with skeleton loaders dedicated for each section that needs to be loaded, whose status will depend on what data is/has been downloaded. Something like that: 
![image](https://github.com/Bartek532/rssmarkable/assets/57185551/bb1ee3e1-698c-45a3-ad57-7ba8d1580224)
